# Generated by Django 4.1.6 on 2023-04-13 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_submission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
