# Generated by Django 4.1.6 on 2023-04-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_boat_classification_delete_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='classification',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='boat',
            name='number',
            field=models.CharField(max_length=4),
        ),
    ]
